{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mflyyou",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 3719,
          "sha512": "1a53a94b68cc1b273241da58a06f1e8462b9e24d8c423499d8a55403c7ff62e63398c52231fe9346d565f8bdcdf0c3a4e0b904f497c9d53c28abc3c224c43400",
          "sha256": "5844f9a2145b0814886fa6c4fa7ad31c0978441a74978aeb751bfab20f8b32e4",
          "sha1": "a845a85eeab521aee1ff40755c9439f0a72df810",
          "md5": "daa539060da4e93cc5a3ed4be3cf0a48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 3719,
          "sha512": "1a53a94b68cc1b273241da58a06f1e8462b9e24d8c423499d8a55403c7ff62e63398c52231fe9346d565f8bdcdf0c3a4e0b904f497c9d53c28abc3c224c43400",
          "sha256": "5844f9a2145b0814886fa6c4fa7ad31c0978441a74978aeb751bfab20f8b32e4",
          "sha1": "a845a85eeab521aee1ff40755c9439f0a72df810",
          "md5": "daa539060da4e93cc5a3ed4be3cf0a48"
        }
      ]
    }
  ]
}
