{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mflyyou",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 3719,
          "sha512": "f338695d1207f227c3d1effcf389a450e3f7a792c612ba0aa5b6139c30bfa21724bc02c5c5e49f8bb48ffb17d31f144b0305ab9af9f5f5873475b95f441eae39",
          "sha256": "8a5cd34e0a49a3c15e5b3818223253173b92bffe3fe312b0acf1409b6026facb",
          "sha1": "f96f27b6a2d4ea392a2b63c4c1cf7b089d1324d9",
          "md5": "8d640abc0a804b9d191406fdd6c40c9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 3719,
          "sha512": "f338695d1207f227c3d1effcf389a450e3f7a792c612ba0aa5b6139c30bfa21724bc02c5c5e49f8bb48ffb17d31f144b0305ab9af9f5f5873475b95f441eae39",
          "sha256": "8a5cd34e0a49a3c15e5b3818223253173b92bffe3fe312b0acf1409b6026facb",
          "sha1": "f96f27b6a2d4ea392a2b63c4c1cf7b089d1324d9",
          "md5": "8d640abc0a804b9d191406fdd6c40c9d"
        }
      ]
    }
  ]
}
