{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mflyyou",
    "module": "common",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.1.1.jar",
          "url": "common-1.1.1.jar",
          "size": 1175,
          "sha512": "f3457da35af2bc3dbb3325455ddd35080a218bc1ea40dc65cf7db0f23a1684cb4798d0020030fc01476bf8f531bd152caf819f808db0106948fea070a2320765",
          "sha256": "c5816f9798d8ce2e14867c2bd37d5bda2a9bd56ef663e6229ec418f8ebf4147a",
          "sha1": "c7aed9c86c9a7891270a1cb304ca7740690ed316",
          "md5": "15ef03bfd154939b4d5456515f6474de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.1.1.jar",
          "url": "common-1.1.1.jar",
          "size": 1175,
          "sha512": "f3457da35af2bc3dbb3325455ddd35080a218bc1ea40dc65cf7db0f23a1684cb4798d0020030fc01476bf8f531bd152caf819f808db0106948fea070a2320765",
          "sha256": "c5816f9798d8ce2e14867c2bd37d5bda2a9bd56ef663e6229ec418f8ebf4147a",
          "sha1": "c7aed9c86c9a7891270a1cb304ca7740690ed316",
          "md5": "15ef03bfd154939b4d5456515f6474de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.1.1-sources.jar",
          "url": "common-1.1.1-sources.jar",
          "size": 903,
          "sha512": "7d2f71fa7d82467079f696ed5bcf2712696ce5c316290cea03c3d1f4a3b3a25d7d6c50881d0bc032958d3e08e652b5e1bc827c1d3e9f13f8352721943becfd6f",
          "sha256": "91846cfb5e536f396ed02d0ea6d71d6aab4d58fe7a41a6ea71db6298bff192d9",
          "sha1": "31b587097ad00dd6fca61dfb988bb87f6cd9508c",
          "md5": "7e2fac30de6d5e098a4ecfccc92518f8"
        }
      ]
    }
  ]
}
