version: '3'
services:
  db:
    image: postgres:12
    container_name: fly-gradle-postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - fly-gradle
  nexus:
    image: sonatype/nexus3
    restart: always
    container_name: fly-gradle-nexus3
    ports:
      - "9908:8081"
    networks:
      - fly-gradle
    volumes:
      - fly-gradle-nexus-data:/nexus-data
  sonarqube:
    image: sonarqube:8.2-community
    restart: always
    container_name: fly-gradle-sonarqube
    depends_on:
      - db
    ports:
      - "9909:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - fly-gradle
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
#  gitlab:
#    image: 'gitlab/gitlab-ee:13.11.6-ee.0'
#    container_name: fly-gradle-gitlab
#    restart: always
#    hostname: 'localhost'
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://localhost:9910'
#    ports:
#      - '9910:80'
#      - '9911:443'
#      - '9912:22'
#    volumes:
#      - gitlib_config:/etc/gitlab
#      - gitlib_logs:/var/log/gitlab
#      - gitlib_data:/var/opt/gitlab
#    networks:
#      - fly-gradle
networks:
  fly-gradle:
    driver: bridge
volumes:
  fly-gradle-nexus-data:
    driver: local
  fly-gradle-sonarqube-data:
    driver: local
  postgresql:
    driver: local
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  gitlib_config:
    driver: local
  gitlib_logs:
    driver: local
  gitlib_data:
    driver: local
